apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-load
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app-load
    spec:
      containers:
        - name: app-load
          image: sashaz/app-load:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always